name: CI Failure Reminder

on:
  workflow_call:

jobs:
  remind-on-failure:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add reminder comment
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          if [[ -n "$PR_NUMBER" ]]; then
            COMMENT_BODY="## CI/CD Pipeline Failure\n\nIt looks like the CI/CD pipeline failed for this PR. Please:\n\n1. **Check the failure logs** to understand what went wrong\n2. **Use pre-commit hooks** to catch these issues locally before pushing\n3. **Ensure your pre-commit hooks are up-to-date** and aligned with the CI/CD pipeline\n4. **Fix the issues** and push the changes\n\nRemember: PRs should not be marked as ready for review until all CI/CD checks pass.\n\nIf the CI/CD caught issues that should have been caught by pre-commit hooks, please update your pre-commit configuration to match the CI/CD pipeline."
            
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" \
              -d "{\"body\":\"${COMMENT_BODY}\"}"
          fi
